[project]
name = "fldpln-hefs"
version = "0.1.0"
description = "This is a python project for retreiving HEFS data and create flood maps using FLDPLN library"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dask>=2025.11.0",
    "fldpln>=0.0.15",
    "ipynb>=0.5.1",
    "matplotlib>=3.10.7",
    "requests>=2.32.5",
    "ipykernel>=7.1.0",
    "distributed>=2025.11.0",
    "openpyxl>=3.1.5",
    "fastparquet>=2024.11.0",
    "leafmap>=0.57.9",
    "xarray>=2025.6.1",
    "ipyleaflet>=0.20.0",
    "localtileserver>=0.10.6",
]
